apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: changpinyanfazhongxin
  description: The changpinyanfazhongxin sub-department
spec:
  type: department
  profile:
    displayName: 产品研发中心
    email: cpyfzx@example.com
    # Intentional no picture for testing
  parent: tianyishuzishanghuo-gz2
  children: [team-tykj-gz, team-tykj-jy, team-tykj-jr]