apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: yunpintaijishuzhongxin
  description: 云平台技术中心
spec:
  type: sub-department
  profile:
    displayName: 云平台技术中心
    email: yptjszx@example.com
    picture: https://avatars.dicebear.com/api/identicon/backstage@example.com.svg?background=%23fff&margin=25
  parent: infrastructure
  children: [team-yunwei]